project:
  type: website
  output-dir: docs

website:
  title: "Oliver Reece"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: Projects.qmd
            text: Academic Projects
          - href: Personal_Projects.qmd
            text: Personal Projects
      - href: Resume.qmd
        text: Resume
      - href: Education.qmd
        text: Education
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



